# Generated by Django 2.2.7 on 2019-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('bus_code', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Bus Code')),
                ('trip_id', models.CharField(max_length=120, verbose_name='Trip Id')),
                ('koridor', models.CharField(max_length=120, verbose_name='Koridor')),
            ],
        ),
    ]
