# Generated by Django 2.2.7 on 2019-12-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_code', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Bus Code')),
                ('trip_id', models.CharField(max_length=120, verbose_name='Trip Id')),
                ('koridor', models.CharField(max_length=120, verbose_name='Koridor')),
                ('gps_timestamp', models.DateField(verbose_name='GPS Timestamp')),
            ],
        ),
        migrations.DeleteModel(
            name='RawData',
        ),
    ]
