# Generated by Django 2.2.7 on 2019-12-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191202_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsPing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_code', models.CharField(max_length=120, verbose_name='Bus Code')),
                ('longitude', models.CharField(max_length=120, verbose_name='Longitude')),
                ('latitude', models.CharField(max_length=120, verbose_name='Latitude')),
                ('gps_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='gps_timestamp',
        ),
        migrations.AddField(
            model_name='bus',
            name='timestamp_epoch',
            field=models.CharField(default=None, max_length=120, verbose_name='Timestamp Epoch'),
            preserve_default=False,
        ),
    ]
